baseURL = 'https://dstarod.github.io/'
languageCode = 'ru-RU'
title = 'Круг интересов'
theme = 'beautiful_hugo'
defaultContentLanguage = 'ru'

[params]
description = 'В основном тут про IT'
# subtitle = 'Reference, Tutorials, and Explanations'

[permalinks]
  [permalinks.page]
    posts = "/posts/:year/:month/:slug/"
    page = "/:slug/"

[markup]
  [markup.highlight]
    style = 'solarized-light'
