baseURL = '/'
languageCode = 'ru-RU'
title = 'Круг интересов'
theme = 'beautiful_hugo'
defaultContentLanguage = 'ru'
enableRobotsTXT = 'true'
summaryLength = 42

[params]
  Description = "В основном тут про IT"

[permalinks]
  [permalinks.page]
    posts = "/posts/:slug/"
    page = "/:slug/"

[markup]
  [markup.highlight]
    style = 'solarized-light'

[menus]
  [[menus.main]]
    name = 'Telegram-канал'
    pre = '<i class="fa-solid fa-code">dd</i>'
    url = 'https://t.me/interests_range'
    weight = 20