baseURL = 'https://dstarod.github.io/'
languageCode = 'ru-RU'
title = 'Круг интересов'
theme = 'ananke'
defaultContentLanguage = "ru"

[params]
description = "В основном тут про IT"
# subtitle = 'Reference, Tutorials, and Explanations'

[permalinks]
  [permalinks.page]
    posts = '/:slug/'
